"""add email to user

Revision ID: a5ef3928b25f
Revises: 0adddddb60db
Create Date: 2025-11-01 17:17:36.502045
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a5ef3928b25f'
down_revision = '0adddddb60db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint('uq_user_email', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_column('role')
        batch_op.drop_column('email')
    # ### end Alembic commands ###
